#!/bin/sh
CROSSCOMPILE=mipsel-linux-
CC=${CROSSCOMPILE}gcc
CXX=${CROSSCOMPILE}g++
STRIP=${CROSSCOMPILE}strip
LD=${CROSSCOMPILE}ld
OBJCOPY=${CROSSCOMPILE}objcopy
CFLAGS="-O2"
export CC CXX STRIP LD CFLAGS
make clean;make distclean
./configure --enable-frame-pointers \
--build=i686-pc-linux-gnu \
--host=mipsel-linux \
--target=mipsel-linux \
--prefix=/root/KTVTest/tcmalloc/install
make;make install
